# Generated by Django 4.0.3 on 2023-01-28 06:03

from django.db import migrations, models
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('subject', models.CharField(max_length=64)),
                ('isbn', isbn_field.fields.ISBNField(max_length=28, primary_key=True, serialize=False, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('author', models.CharField(max_length=64)),
                ('kinds_of_books', models.CharField(choices=[('CG', 'COMPUTER_GENERAL'), ('PP', 'PHILOSOPHY_PSYCHOLOGY'), ('RE', 'RELIGION'), ('SO', 'SOCIAL'), ('LA', 'LANGUAGE'), ('SC', 'SCIENCE'), ('TE', 'TECHNOLOGY'), ('AR', 'ARTS_RECREATION'), ('LI', 'LITERATURE'), ('HG', 'HISTORY_GEOGRAPHY')], default='CG', max_length=2)),
                ('count', models.PositiveIntegerField()),
                ('register_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
