# Generated by Django 4.0.3 on 2023-01-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRT_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='book',
            name='kinds_of_books',
            field=models.CharField(choices=[('CG', 'COMPUTER_GENERAL'), ('PP', 'PHILOSOPHY_PSYCHOLOGY'), ('RE', 'RELIGION'), ('SO', 'SOCIAL'), ('LA', 'LANGUAGE'), ('SC', 'SCIENCE'), ('TE', 'TECHNOLOGY'), ('AR', 'ARTS_RECREATION'), ('LI', 'LITERATURE'), ('HG', 'HISTORY_GEOGRAPHY')], default='CG', max_length=2),
        ),
    ]
