# Generated by Django 4.0.3 on 2023-01-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRRT_library', '0004_remove_book_id_alter_book_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='register_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
